// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	universe "github.com/petherin/onto/internal/domain/universe"
	mock "github.com/stretchr/testify/mock"
)

// MockLocationGenerator is an autogenerated mock type for the LocationGenerator type
type MockLocationGenerator struct {
	mock.Mock
}

type MockLocationGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationGenerator) EXPECT() *MockLocationGenerator_Expecter {
	return &MockLocationGenerator_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: u, id, coord
func (_m *MockLocationGenerator) Handle(u *universe.Universe, id string, coord universe.Coordinate) bool {
	ret := _m.Called(u, id, coord)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*universe.Universe, string, universe.Coordinate) bool); ok {
		r0 = rf(u, id, coord)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockLocationGenerator_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockLocationGenerator_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - u *universe.Universe
//   - id string
//   - coord universe.Coordinate
func (_e *MockLocationGenerator_Expecter) Handle(u interface{}, id interface{}, coord interface{}) *MockLocationGenerator_Handle_Call {
	return &MockLocationGenerator_Handle_Call{Call: _e.mock.On("Handle", u, id, coord)}
}

func (_c *MockLocationGenerator_Handle_Call) Run(run func(u *universe.Universe, id string, coord universe.Coordinate)) *MockLocationGenerator_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*universe.Universe), args[1].(string), args[2].(universe.Coordinate))
	})
	return _c
}

func (_c *MockLocationGenerator_Handle_Call) Return(_a0 bool) *MockLocationGenerator_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationGenerator_Handle_Call) RunAndReturn(run func(*universe.Universe, string, universe.Coordinate) bool) *MockLocationGenerator_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocationGenerator creates a new instance of MockLocationGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationGenerator {
	mock := &MockLocationGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
