// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	universe "github.com/petherin/onto/internal/domain/universe"
)

// MockPathfinderService is an autogenerated mock type for the PathfinderService type
type MockPathfinderService struct {
	mock.Mock
}

type MockPathfinderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPathfinderService) EXPECT() *MockPathfinderService_Expecter {
	return &MockPathfinderService_Expecter{mock: &_m.Mock}
}

// FindRoute provides a mock function with given fields: u, from, to
func (_m *MockPathfinderService) FindRoute(u *universe.Aggregate, from string, to string) ([]universe.EdgeVO, bool) {
	ret := _m.Called(u, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindRoute")
	}

	var r0 []universe.EdgeVO
	var r1 bool
	if rf, ok := ret.Get(0).(func(*universe.Aggregate, string, string) ([]universe.EdgeVO, bool)); ok {
		return rf(u, from, to)
	}
	if rf, ok := ret.Get(0).(func(*universe.Aggregate, string, string) []universe.EdgeVO); ok {
		r0 = rf(u, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]universe.EdgeVO)
		}
	}

	if rf, ok := ret.Get(1).(func(*universe.Aggregate, string, string) bool); ok {
		r1 = rf(u, from, to)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockPathfinderService_FindRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRoute'
type MockPathfinderService_FindRoute_Call struct {
	*mock.Call
}

// FindRoute is a helper method to define mock.On call
//   - u *universe.Aggregate
//   - from string
//   - to string
func (_e *MockPathfinderService_Expecter) FindRoute(u interface{}, from interface{}, to interface{}) *MockPathfinderService_FindRoute_Call {
	return &MockPathfinderService_FindRoute_Call{Call: _e.mock.On("FindRoute", u, from, to)}
}

func (_c *MockPathfinderService_FindRoute_Call) Run(run func(u *universe.Aggregate, from string, to string)) *MockPathfinderService_FindRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*universe.Aggregate), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPathfinderService_FindRoute_Call) Return(_a0 []universe.EdgeVO, _a1 bool) *MockPathfinderService_FindRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPathfinderService_FindRoute_Call) RunAndReturn(run func(*universe.Aggregate, string, string) ([]universe.EdgeVO, bool)) *MockPathfinderService_FindRoute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPathfinderService creates a new instance of MockPathfinderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPathfinderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPathfinderService {
	mock := &MockPathfinderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
