// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	universe "github.com/petherin/onto/internal/domain/universe"
	mock "github.com/stretchr/testify/mock"
)

// MockLocationGeneratorService is an autogenerated mock type for the LocationGeneratorService type
type MockLocationGeneratorService struct {
	mock.Mock
}

type MockLocationGeneratorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationGeneratorService) EXPECT() *MockLocationGeneratorService_Expecter {
	return &MockLocationGeneratorService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: u, originID, coordinate
func (_m *MockLocationGeneratorService) Generate(u *universe.Aggregate, originID string, coordinate universe.CoordinateVO) ([]universe.LocationEntity, []universe.EdgeVO, error) {
	ret := _m.Called(u, originID, coordinate)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 []universe.LocationEntity
	var r1 []universe.EdgeVO
	var r2 error
	if rf, ok := ret.Get(0).(func(*universe.Aggregate, string, universe.CoordinateVO) ([]universe.LocationEntity, []universe.EdgeVO, error)); ok {
		return rf(u, originID, coordinate)
	}
	if rf, ok := ret.Get(0).(func(*universe.Aggregate, string, universe.CoordinateVO) []universe.LocationEntity); ok {
		r0 = rf(u, originID, coordinate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]universe.LocationEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*universe.Aggregate, string, universe.CoordinateVO) []universe.EdgeVO); ok {
		r1 = rf(u, originID, coordinate)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]universe.EdgeVO)
		}
	}

	if rf, ok := ret.Get(2).(func(*universe.Aggregate, string, universe.CoordinateVO) error); ok {
		r2 = rf(u, originID, coordinate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLocationGeneratorService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockLocationGeneratorService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - u *universe.Aggregate
//   - originID string
//   - coordinate universe.CoordinateVO
func (_e *MockLocationGeneratorService_Expecter) Generate(u interface{}, originID interface{}, coordinate interface{}) *MockLocationGeneratorService_Generate_Call {
	return &MockLocationGeneratorService_Generate_Call{Call: _e.mock.On("Generate", u, originID, coordinate)}
}

func (_c *MockLocationGeneratorService_Generate_Call) Run(run func(u *universe.Aggregate, originID string, coordinate universe.CoordinateVO)) *MockLocationGeneratorService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*universe.Aggregate), args[1].(string), args[2].(universe.CoordinateVO))
	})
	return _c
}

func (_c *MockLocationGeneratorService_Generate_Call) Return(_a0 []universe.LocationEntity, _a1 []universe.EdgeVO, _a2 error) *MockLocationGeneratorService_Generate_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLocationGeneratorService_Generate_Call) RunAndReturn(run func(*universe.Aggregate, string, universe.CoordinateVO) ([]universe.LocationEntity, []universe.EdgeVO, error)) *MockLocationGeneratorService_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocationGeneratorService creates a new instance of MockLocationGeneratorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationGeneratorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationGeneratorService {
	mock := &MockLocationGeneratorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
