// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	universe "github.com/petherin/onto/internal/domain/universe"
	mock "github.com/stretchr/testify/mock"
)

// MockLocationGeneratorService is an autogenerated mock type for the LocationGeneratorService type
type MockLocationGeneratorService struct {
	mock.Mock
}

type MockLocationGeneratorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationGeneratorService) EXPECT() *MockLocationGeneratorService_Expecter {
	return &MockLocationGeneratorService_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: u, id, coord
func (_m *MockLocationGeneratorService) Handle(u *universe.Aggregate, id string, coord universe.CoordinateVO) bool {
	ret := _m.Called(u, id, coord)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*universe.Aggregate, string, universe.CoordinateVO) bool); ok {
		r0 = rf(u, id, coord)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockLocationGeneratorService_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockLocationGeneratorService_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - u *universe.Aggregate
//   - id string
//   - coord universe.CoordinateVO
func (_e *MockLocationGeneratorService_Expecter) Handle(u interface{}, id interface{}, coord interface{}) *MockLocationGeneratorService_Handle_Call {
	return &MockLocationGeneratorService_Handle_Call{Call: _e.mock.On("Handle", u, id, coord)}
}

func (_c *MockLocationGeneratorService_Handle_Call) Run(run func(u *universe.Aggregate, id string, coord universe.CoordinateVO)) *MockLocationGeneratorService_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*universe.Aggregate), args[1].(string), args[2].(universe.CoordinateVO))
	})
	return _c
}

func (_c *MockLocationGeneratorService_Handle_Call) Return(_a0 bool) *MockLocationGeneratorService_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationGeneratorService_Handle_Call) RunAndReturn(run func(*universe.Aggregate, string, universe.CoordinateVO) bool) *MockLocationGeneratorService_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocationGeneratorService creates a new instance of MockLocationGeneratorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationGeneratorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationGeneratorService {
	mock := &MockLocationGeneratorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
