// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	universe "github.com/petherin/onto/internal/domain/universe"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the UniverseRepository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with no fields
func (_m *MockRepository) Load() (*universe.UniverseAggregate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *universe.UniverseAggregate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*universe.UniverseAggregate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *universe.UniverseAggregate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*universe.UniverseAggregate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Load() *MockRepository_Load_Call {
	return &MockRepository_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockRepository_Load_Call) Run(run func()) *MockRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Load_Call) Return(_a0 *universe.UniverseAggregate, _a1 error) *MockRepository_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Load_Call) RunAndReturn(run func() (*universe.UniverseAggregate, error)) *MockRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: u
func (_m *MockRepository) Save(u *universe.UniverseAggregate) error {
	ret := _m.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*universe.UniverseAggregate) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - u *universe.UniverseAggregate
func (_e *MockRepository_Expecter) Save(u interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", u)}
}

func (_c *MockRepository_Save_Call) Run(run func(u *universe.UniverseAggregate)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*universe.UniverseAggregate))
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(_a0 error) *MockRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(*universe.UniverseAggregate) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
