// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	universe "github.com/petherin/onto/internal/domain/universe"
)

// MockPathfinder is an autogenerated mock type for the PathfinderService type
type MockPathfinder struct {
	mock.Mock
}

type MockPathfinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPathfinder) EXPECT() *MockPathfinder_Expecter {
	return &MockPathfinder_Expecter{mock: &_m.Mock}
}

// FindRoute provides a mock function with given fields: u, from, to
func (_m *MockPathfinder) FindRoute(u *universe.UniverseAggregate, from string, to string) ([]universe.EdgeVO, bool) {
	ret := _m.Called(u, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindRoute")
	}

	var r0 []universe.EdgeVO
	var r1 bool
	if rf, ok := ret.Get(0).(func(*universe.UniverseAggregate, string, string) ([]universe.EdgeVO, bool)); ok {
		return rf(u, from, to)
	}
	if rf, ok := ret.Get(0).(func(*universe.UniverseAggregate, string, string) []universe.EdgeVO); ok {
		r0 = rf(u, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]universe.EdgeVO)
		}
	}

	if rf, ok := ret.Get(1).(func(*universe.UniverseAggregate, string, string) bool); ok {
		r1 = rf(u, from, to)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockPathfinder_FindRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRoute'
type MockPathfinder_FindRoute_Call struct {
	*mock.Call
}

// FindRoute is a helper method to define mock.On call
//   - u *universe.UniverseAggregate
//   - from string
//   - to string
func (_e *MockPathfinder_Expecter) FindRoute(u interface{}, from interface{}, to interface{}) *MockPathfinder_FindRoute_Call {
	return &MockPathfinder_FindRoute_Call{Call: _e.mock.On("FindRoute", u, from, to)}
}

func (_c *MockPathfinder_FindRoute_Call) Run(run func(u *universe.UniverseAggregate, from string, to string)) *MockPathfinder_FindRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*universe.UniverseAggregate), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPathfinder_FindRoute_Call) Return(_a0 []universe.EdgeVO, _a1 bool) *MockPathfinder_FindRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPathfinder_FindRoute_Call) RunAndReturn(run func(*universe.UniverseAggregate, string, string) ([]universe.EdgeVO, bool)) *MockPathfinder_FindRoute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPathfinder creates a new instance of MockPathfinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPathfinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPathfinder {
	mock := &MockPathfinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
