with-expecter: true
inpackage: false
dir: "internal/mocks"
outpkg: "mocks"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  github.com/petherin/onto/internal/domain/universe:
    interfaces:
      Repository:
      LocationGeneratorService:
  github.com/petherin/onto/internal/domain/navigation:
    interfaces:
      PathfinderService:
