#!/usr/bin/env bash
# LOCAL-ONLY MiniStack runtime shim, invoked by shim.tf after Terraform has
# created the ECS cluster/task-def, ALB, target group and listener. It starts the
# API container (run-task), registers it with the target group, and wires the
# nginx edge to the ALB's freshly-generated DNS name. On real AWS the ECS service
# does all of this natively, so none of this exists in envs/aws.
set -euo pipefail

awsm() { aws --endpoint-url "$ONTO_ENDPOINT" "$@"; }
say()  { printf '\n\033[1;36m== %s\033[0m\n' "$*"; }

# ── Clear any previous task/containers so we don't pile up stale API instances ──
say "ECS: clearing previous tasks"
for t in $(awsm ecs list-tasks --cluster "$CLUSTER" --query 'taskArns[]' --output text 2>/dev/null); do
  awsm ecs stop-task --cluster "$CLUSTER" --task "$t" >/dev/null 2>&1 || true
done
docker ps -aq --filter 'name=ministack-ecs-' | xargs -r docker rm -f >/dev/null 2>&1 || true

# ── Run the task and find the container it started ─────────────────────────────
say "ECS: run-task $TASK_FAMILY"
TASK_ARN="$(awsm ecs run-task --cluster "$CLUSTER" --task-definition "$TASK_FAMILY" \
  --launch-type FARGATE \
  --network-configuration "awsvpcConfiguration={subnets=[$SUBNET],assignPublicIp=ENABLED}" \
  --query 'tasks[0].taskArn' --output text)"
SHORT="${TASK_ARN##*/}"; SHORT="${SHORT%%-*}"
CT_NAME="ministack-ecs-${SHORT}-api"
IP=""
for _ in $(seq 1 30); do
  IP="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$CT_NAME" 2>/dev/null || true)"
  [ -n "$IP" ] && break
  sleep 1
done
[ -n "$IP" ] || { echo "ERROR: API container $CT_NAME did not start" >&2; exit 1; }
printf '  task %s -> container %s @ %s\n' "$SHORT" "$CT_NAME" "$IP"

# ── Register the container IP with the ALB target group ────────────────────────
say "ALB: register target $IP:$API_PORT"
awsm elbv2 register-targets --target-group-arn "$TG_ARN" \
  --targets "Id=$IP,Port=$API_PORT" >/dev/null

# ── Edge: point api.onto.world at this run's ALB DNS ───────────────────────────
say "Edge: wiring api.onto.world -> $ALB_DNS"
cat > "$NGINX_CONF_DIR/api.conf" <<EOF
# Generated by shim.sh (Terraform local env) — routes api.onto.world to the ALB by
# rewriting Host to the ALB's DNS name (the only host MiniStack's ALB answers to).
server {
    listen 80;
    server_name api.onto.world;
    location / {
        proxy_pass http://ministack:4566;
        proxy_set_header Host $ALB_DNS;
    }
}
EOF
docker exec "$EDGE_CONTAINER" nginx -s reload >/dev/null 2>&1 || true

say "Done"
cat <<EOF
  SPA : http://onto.world/                (S3 bucket onto-web)
  API : http://api.onto.world/api/state   (ALB -> ECS)
  Ensure /etc/hosts maps both to 127.0.0.1:  make ministack-hosts
EOF
